# Generated by Django 3.2.7 on 2021-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=10)),
                ('p_price', models.IntegerField(default=0)),
                ('p_id', models.IntegerField(max_length=2)),
                ('p_image', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
