# Generated by Django 3.2.7 on 2021-09-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_id',
        ),
    ]
