# Generated by Django 3.2.7 on 2021-09-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myweb', '0002_remove_product_p_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
