# Generated by Django 3.2.7 on 2021-09-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myweb', '0004_product_p_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
