# Generated by Django 3.2.7 on 2021-09-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myweb', '0005_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
