# Generated by Django 3.2.7 on 2021-09-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myweb', '0006_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_costumname', models.CharField(default='', max_length=50)),
                ('o_costumaddress', models.CharField(default='', max_length=100)),
                ('o_costumphone', models.CharField(default='', max_length=50)),
                ('o_subtotal', models.IntegerField(default=0)),
                ('o_shipping', models.IntegerField(default=0)),
                ('o_grandtotal', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
